# Generated by Django 5.0.6 on 2024-05-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin_main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='s3_key',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
    ]
