# Generated by Django 5.0.6 on 2024-05-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin_main_app', '0003_alter_metadata_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='s3_key',
            field=models.CharField(default=1, max_length=80, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadata',
            name='timestamp',
            field=models.CharField(max_length=50),
        ),
    ]
