# Generated by Django 5.0.6 on 2024-05-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin_main_app', '0004_alter_metadata_s3_key_alter_metadata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='s3_key',
            field=models.CharField(default='trollkey', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='timestamp',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='user_agent',
            field=models.CharField(max_length=150),
        ),
    ]
